### ISSUE TITLE
Dealer can get an impossible hand, leads to deal(press any key) not working when user hits a key

### ISSUE THREAD

**Issue by cmlcode** [mhluska/blackjack-simulator#64]
![image](https://github.com/mhluska/blackjack-simulator/assets/61091285/c5c58d68-b5cb-4dec-ae10-237784933afb)

When user presses normal play button (s, h), it plays the action on their next hand as seen here (after pressing s):

![image](https://github.com/mhluska/blackjack-simulator/assets/61091285/e3f29eec-0a74-4bb0-acba-2f51ce5f503b)

If any other button is pressed, nothing happens.

**Comment by mhluska** [comment]
Thanks for the bug report. I think the issue here is that deal is only triggered by certain keys rather than any key as it says. I can fix that.

The other part about it playing the next hand seems to just be losing immediately to the dealer's blackjack. I could update the text to make it more clear.
